spring:
  rabbitmq:
    host: 192.168.11.47
    username: root
    password: 123456
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
# 发布确认回调开启 交换机
    publisher-confirm-type: correlated
# 消息回退开启
    publisher-returns: true
server:
  port: 8080