spring:
  rabbitmq:
    host: 192.168.11.47
    username: root
    password: 123456
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false

server:
  port: 8080